# Generated by Django 3.2 on 2023-01-25 20:55

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sku',
            field=models.CharField(blank=True, default=stock.models.Stock.create_new_sku, editable=False, max_length=254, null=True, unique=True),
        ),
    ]
