# Generated by Django 3.2 on 2023-02-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='gift',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
    ]
