# Generated by Django 3.2 on 2023-03-27 20:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20230327_2002'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(check=models.Q(price__gte=Decimal('0.01')), name='price_positive'),
        ),
    ]
